### ISSUE TITLE
Workflow fail when `image_version` is not provided

### ISSUE THREAD

**Issue by gpelouze** [QCDIS/NaaVRE-cells#3]
When building cells from an older version of NaaVRE that doesn't provide `image_version`, the workflow fails with eg ([workflow](https://github.com/QCDIS/NaaVRE-cells-test-2/actions/runs/7709539543/job/21010971010)):

```
ERROR: invalid tag "ghcr.io/qcdis/naavre-cells-test-2/my-cell-my-user:": invalid reference format
```

If `github.event.inputs.image_version` is not set, we should fall-back to the old behavior of using `steps.commit.outputs.short`, or not setting a tag at all.

**Comment by skoulouzis** [comment]
I'll make sure that we are backward compatible if I add this
